export const recomendation = {
    "bann@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "ben@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "boa@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "yub@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "vol@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "vog@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "guk@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "eva@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "aer@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "hrd@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "idm@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "kaa@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "ek@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "ki@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "fin@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "lad@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "mev@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "valp@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "peg@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "ram@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "rua@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "rir@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "rek@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "sae@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "fs@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "stm@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "nis@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "as@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "un@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "evu@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "dfi@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "shi@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "enn@somedomain.com": "Набережная реки Тура, Контора Пароходства, Бульвар Дзержинского",
    "aba@somedomain.com": null,
    "abr@somedomain.com": null,
    "ahi@somedomain.com": null,
    "mba@somedomain.com": null,
    "vav@somedomain.com": null,
    "gak@somedomain.com": null,
    "gou@somedomain.com": null,
    "dma@somedomain.com": null,
    "zvd@somedomain.com": null,
    "ok@somedomain.com": "Всё!",
    "kot@somedomain.com": null,
    "kud@somedomain.com": null,
    "bok@somedomain.com": null,
    "mod@somedomain.com": null,
    "mukd@somedomain.com": null,
    "nem@somedomain.com": "Всё!",
    "ovv@somedomain.com": null,
    "saa@somedomain.com": null,
    "das@somedomain.com": null,
    "son@somedomain.com": null,
    "kha@somedomain.com": null,
    "har@somedomain.com": null,
    "hoa@somedomain.com": null,
    "vsh@somedomain.com": null
};