import { 
  project_3, 
  project_8, 
  project_5, 
  project_10, 
  project_9, 
  project_11, 
  project_4, 
  project_7, 
  project_6, 
  project_1, 
  project_2 
} from "entities/project/project.constants";
import { IUser } from "entities/user/user.types";

export const people: IUser[] = [
    {
      "@type": "User",
      "@id": "/api/users/aba-somadomain-ru",
      "email": "aba@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-11-16T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:1531",
        "firstName": "Амаль",
        "lastName": "Абдуллаев",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 4
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/17268a86-780b-11eb-9b2e-8eef8963d819",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_1,
        project_3
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/189",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 1 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/abr-somadomain-ru",
      "email": "abr@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-09-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:1755",
        "firstName": "Александр",
        "lastName": "Абрамов",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 3
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/836d32fa-bd41-11eb-af31-921441fde351",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_9,
        project_4,
        project_5,
        project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/191",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Специалист по ручному тестированию в области информационных технологий 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/admin-somadomain-ru",
      "email": "admin@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:1993",
        "firstName": "Creative",
        "lastName": "Администратор",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": null
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/8d608e28-323b-11ec-a6f3-c638cbfd3fef",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/79d181f8-56fb-11eb-9a4e-cbc7a73c1ca7",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [],
      "isAdmin": true,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/ahi-somadomain-ru",
      "email": "ahi@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2197",
        "firstName": "Ирина",
        "lastName": "Ахтимирова",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 2
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/6c95add8-81d9-11ed-ba57-e68f55acb25e",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/04ec213c-7c50-11ed-ac52-e68f55acb25e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
        project_10,
        project_11,
        project_5,
        project_9,
      ],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/seb-somadomain-ru",
      "email": "seb@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-03-29T00:00:00+05:00",
      "dateDismissal": "2023-01-31T00:00:00+05:00",
      "person": {
        "@type": "Person",
        "@id": "_:2528",
        "firstName": "Сергей",
        "lastName": "Балтасев",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/4aaf7788-9065-11eb-822e-12e2accc0323",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/bann-somadomain-ru",
      "email": "bann@somedomain.com",
      "contacts": [],
      "dateHiring": "2023-02-06T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2738",
        "firstName": "Мария",
        "lastName": "Банникова",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/f47d7ece-a5e2-11ed-8cc8-d2ad45816a6c",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_4,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/284",
        "@type": "WorkPosition",
        "datePosition": "2023-02-06T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "self_employed_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/mba-somadomain-ru",
      "email": "mba@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-06-17T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2902",
        "firstName": "Марк",
        "lastName": "Басов",
        "surname": "Андреевич",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 2
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/e67b22a4-56fc-11eb-933f-13d81d7276c8",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_2
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/288",
        "@type": "WorkPosition",
        "datePosition": "2023-02-03T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/ben-somadomain-ru",
      "email": "ben@somedomain.com",
      "contacts": [],
      "dateHiring": "2023-02-15T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3017",
        "firstName": "Наталья",
        "lastName": "Бельская",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/f1b3f7d8-ad06-11ed-b779-ea3e34fa79ed",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_6,
        project_4,
project_1,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/289",
        "@type": "WorkPosition",
        "datePosition": "2023-02-15T00:00:00+05:00",
        "jobTitle": "Аналитик 3 категории ",
        "contractType": "self_employed_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/byu-somadomain-ru",
      "email": "byu@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-04-12T00:00:00+05:00",
      "dateDismissal": "2022-09-30T00:00:00+05:00",
      "person": {
        "@type": "Person",
        "@id": "_:3144",
        "firstName": "Юлия",
        "lastName": "Бирюкова",
        "surname": "Алексеевна",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 2
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/daf57cae-9b67-11eb-8b65-96363185a123",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/boa-somadomain-ru",
      "email": "boa@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-06-08T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3172",
        "firstName": "Андрей",
        "lastName": "Бочагов",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/c5d8c89e-e6f7-11ec-979f-3e270bb22133",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_9
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/198",
        "@type": "WorkPosition",
        "datePosition": "2022-09-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/yub-somadomain-ru",
      "email": "yub@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-04-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3267",
        "firstName": "Юрий",
        "lastName": "Бочаров",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/250c1c74-780b-11eb-9b2e-8eef8963d819",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_4
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/253",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 1 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/vav-somadomain-ru",
      "email": "vav@somedomain.com",
      "contacts": [],
      "dateHiring": "2023-04-17T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3453",
        "firstName": "Вадим",
        "lastName": "Васьковцов",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 2
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/604041c6-dd17-11ed-87fd-6e96a8b65f3e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_4
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/292",
        "@type": "WorkPosition",
        "datePosition": "2023-04-17T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/vol-somadomain-ru",
      "email": "vol@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-06-17T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3541",
        "firstName": "Ярослав",
        "lastName": "Волох",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/3e80fa2c-462b-11ed-bc1a-7a6aa26374bc",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/281769c6-cf38-11eb-afd3-06d5ef3c9008",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
project_1,
        project_2
      ],
      "projectsAsDeveloper": [
        project_6,
        project_4,
project_1,
        project_7
      ],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/250",
        "@type": "WorkPosition",
        "datePosition": "2022-06-07T00:00:00+05:00",
        "jobTitle": "Технический эксперт 3 категории ",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/vog-somadomain-ru",
      "email": "vog@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-08-06T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3573",
        "firstName": "Григорий",
        "lastName": "Волчок",
        "surname": "Владимирович",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/3144d874-462b-11ed-8782-7a6aa26374bc",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/2f25f0ec-f67b-11eb-b6c3-325b06ee5663",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
project_1,
        project_2
      ],
      "projectsAsDeveloper": [
        project_9,
        project_6,
project_1,
        project_4,
        project_11
      ],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/199",
        "@type": "WorkPosition",
        "datePosition": "2022-07-01T00:00:00+05:00",
        "jobTitle": "Технический эксперт 3 категории",
        "contractType": "labor_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/gak-somadomain-ru",
      "email": "gak@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-09-14T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3606",
        "firstName": "Карина",
        "lastName": "Габайдуллина",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 6
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/1faa45fa-15e8-11ec-8fb3-325b06ee5663",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_7
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/137",
        "@type": "WorkPosition",
        "datePosition": "2021-09-14T00:00:00+05:00",
        "jobTitle": "Дизайнер 2 категории (Middle)",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/gou-somadomain-ru",
      "email": "gou@somedomain.com",
      "contacts": [],
      "dateHiring": "2023-04-03T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3629",
        "firstName": "Юлия",
        "lastName": "Голякова",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 13
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/2da16e60-d20a-11ed-b3bb-6e96a8b65f3e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_4,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/291",
        "@type": "WorkPosition",
        "datePosition": "2023-04-03T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "self_employed_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/guk-somadomain-ru",
      "email": "guk@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-08-02T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3666",
        "firstName": "Константин",
        "lastName": "Гудович",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/ae6b1122-1234-11ed-8656-da7fec29a547",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_4,
project_1,
        project_10,
        project_8
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/178",
        "@type": "WorkPosition",
        "datePosition": "2022-09-01T00:00:00+05:00",
        "jobTitle": "Аналитик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/dma-somadomain-ru",
      "email": "dma@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-12-21T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3825",
        "firstName": "Александр",
        "lastName": "Дмитриев",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 12
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/5724051e-8119-11ed-b3c2-e68f55acb25e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_11
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/285",
        "@type": "WorkPosition",
        "datePosition": "2022-12-21T00:00:00+05:00",
        "jobTitle": "Ведущий бэкенд разработчик на Symfony",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/eva-somadomain-ru",
      "email": "eva@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-02-21T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3880",
        "firstName": "Андрей",
        "lastName": "Евдошенко",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/b4a63c1e-17e9-11ed-8d1f-fe6263566c11",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/b33f54c4-a9bb-11ec-8422-5ac6cb191788",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
project_1,
        project_2
      ],
      "projectsAsDeveloper": [
        project_4,
        project_6,
      ],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": {
        "@id": "/api/work-positions/48",
        "@type": "WorkPosition",
        "datePosition": "2022-02-21T00:00:00+05:00",
        "jobTitle": "Технический эксперт 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/aer-somadomain-ru",
      "email": "aer@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-03-16T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3877",
        "firstName": "Анастасия",
        "lastName": "Ермакова",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/9f819610-56fe-11eb-ad07-d7b5ab64ec6d",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_11,
project_1,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/202",
        "@type": "WorkPosition",
        "datePosition": "2022-07-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/zvd-somadomain-ru",
      "email": "zvd@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3914",
        "firstName": "Денис",
        "lastName": "Звонарев",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 2
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/2a192080-a221-11ed-8f24-d2ad45816a6c",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/8955f50e-a218-11ed-b78e-d2ad45816a6c",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
        project_7,
        project_6
      ],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/hrd-somadomain-ru",
      "email": "hrd@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3965",
        "firstName": "Наталья",
        "lastName": "Изотова",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/10ddddfa-4636-11ed-8e19-7a6aa26374bc",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": null,
      "projectsAsManager": [
        project_4
      ],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": false,
      "isHR": true,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/idm-somadomain-ru",
      "email": "idm@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-07-22T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:3997",
        "firstName": "Дмитрий",
        "lastName": "Икрин",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/101b0a12-91f3-11eb-8e3a-12e2accc0323",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/0f306908-56fc-11eb-9c4c-9762c0742e1a",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
project_1,
        project_2,
      ],
      "projectsAsDeveloper": [
        project_6,
        project_4,
project_1,
      ],
      "isAdmin": true,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": {
        "@id": "/api/work-positions/205",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Ведущий технический эксперт",
        "contractType": "labor_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/kaa-somadomain-ru",
      "email": "kaa@somedomain.com",
      "contacts": [],
      "dateHiring": "2019-07-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4050",
        "firstName": "Андрей",
        "lastName": "Казанцев",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/4d2b424e-7a4e-11eb-99da-fe7d46a14155",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/281",
        "@type": "WorkPosition",
        "datePosition": "2023-02-01T00:00:00+05:00",
        "jobTitle": "Разработчик 1 категории",
        "contractType": "self_employed_contract",
        "normFullDay": 8,
        "normShortDay": 8,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/ek-somadomain-ru",
      "email": "ek@somedomain.com",
      "contacts": [],
      "dateHiring": "2015-07-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4103",
        "firstName": "Екатерина",
        "lastName": "Казеко",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/0b7fc7e8-462b-11ed-bd8d-7a6aa26374bc",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/338ed3f0-5aff-11eb-afe5-2b670db71f46",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
        project_2,
project_1
      ],
      "projectsAsDeveloper": [
        project_4,
        project_7,
        project_6,
      ],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/211",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Технический эксперт 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/ki-somadomain-ru",
      "email": "ki@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-03-02T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4281",
        "firstName": "Иван",
        "lastName": "Кирюхин",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/9e0b8ff0-56fb-11eb-8d5d-dd672552debd",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_8,
        project_5
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/213",
        "@type": "WorkPosition",
        "datePosition": "2021-07-01T00:00:00+05:00",
        "jobTitle": "Фронтенд разработчик",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/fin-somadomain-ru",
      "email": "fin@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4302",
        "firstName": "Людмила",
        "lastName": "Клименко",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/bd7d5ff0-12f5-11ed-9ea1-da7fec29a547",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": null,
      "projectsAsManager": [],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": true,
      "isDeveloper": false,
      "isHR": true,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/ok-somadomain-ru",
      "email": "ok@somedomain.com",
      "contacts": [],
      "dateHiring": "2017-05-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4312",
        "firstName": "Олег",
        "lastName": "Кольцов",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 19
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/1f6a8e8e-56fc-11eb-b238-89d53615d7fb",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_8,
        project_6
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/215",
        "@type": "WorkPosition",
        "datePosition": "2022-07-01T00:00:00+05:00",
        "jobTitle": "Разработчик 1 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/kot-somadomain-ru",
      "email": "kot@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-01-11T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4358",
        "firstName": "Тимур",
        "lastName": "Костенко",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 2
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/4ff39a4e-5aff-11eb-a279-e116f0255db6",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/282",
        "@type": "WorkPosition",
        "datePosition": "2023-02-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "self_employed_contract",
        "normFullDay": 8,
        "normShortDay": 8,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/kud-somadomain-ru",
      "email": "kud@somedomain.com",
      "contacts": [],
      "dateHiring": "2023-04-17T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4381",
        "firstName": "Дмитрий",
        "lastName": "",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 14
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/dd495542-dd15-11ed-bd42-6e96a8b65f3e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_4,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/293",
        "@type": "WorkPosition",
        "datePosition": "2023-04-17T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "self_employed_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/bok-somadomain-ru",
      "email": "bok@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-07-27T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4395",
        "firstName": "Богдан",
        "lastName": "Кузьмин",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 18
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/347f61e0-eebf-11eb-8f26-325b06ee5663",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_2,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/60",
        "@type": "WorkPosition",
        "datePosition": "2021-07-27T00:00:00+05:00",
        "jobTitle": "Разработчик 3 категории ",
        "contractType": "foreigner_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/lad-somadomain-ru",
      "email": "lad@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-10-06T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4415",
        "firstName": "Денис",
        "lastName": "Ламбин",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/f3015034-c506-11eb-9509-12be5af29b77",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/217",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 3 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/mev-somadomain-ru",
      "email": "mev@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-05-26T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4509",
        "firstName": "Евгений",
        "lastName": "Микитка",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/610ecd52-bde3-11eb-b413-921441fde351",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/260",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории ",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/mod-somadomain-ru",
      "email": "mod@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-10-28T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4550",
        "firstName": "Даниил",
        "lastName": "Могильный",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 4
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/768af5a0-5706-11eb-9e51-bdf9167b7f1a",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_4,
        project_11,
        project_2,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/224",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 1 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/mukd-somadomain-ru",
      "email": "mukd@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-01-24T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4559",
        "firstName": "Дастан",
        "lastName": "Мукажан",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 15
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/7ed1f62e-7ce8-11ec-bbc5-a6ce6b46d73a",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_9,
        project_2
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/122",
        "@type": "WorkPosition",
        "datePosition": "2022-01-24T00:00:00+05:00",
        "jobTitle": "разработчик",
        "contractType": "foreigner_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/nem-somadomain-ru",
      "email": "nem@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-06-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4608",
        "firstName": "Михаил",
        "lastName": "Невтыра",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 19
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/273ccc08-56fc-11eb-8f21-275f5f1381d2",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/225",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/ovv-somadomain-ru",
      "email": "ovv@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4643",
        "firstName": "Виталий",
        "lastName": "Овсяников",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 16
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/d05c6de0-d542-11ed-b459-6e96a8b65f3e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/valp-somadomain-ru",
      "email": "valp@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-09-03T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4657",
        "firstName": "Валерий",
        "lastName": "Пальянов",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/c2814708-56fb-11eb-b093-edcff85c9b73",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_5,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/271",
        "@type": "WorkPosition",
        "datePosition": "2022-11-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/peg-somadomain-ru",
      "email": "peg@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-06-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4691",
        "firstName": "Геннадий",
        "lastName": "Перятин",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/da64f624-7980-11eb-b707-bea64491cdb5",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_11,
        project_10
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/72",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/ram-somadomain-ru",
      "email": "ram@somedomain.com",
      "contacts": [],
      "dateHiring": "2023-02-21T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4770",
        "firstName": "Михаил",
        "lastName": "Расторгуев",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/5312a074-b1df-11ed-bd11-d2cca3565f1f",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_9,
        project_6,
project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/286",
        "@type": "WorkPosition",
        "datePosition": "2023-02-21T00:00:00+05:00",
        "jobTitle": "Веб-дизайнер 2 категории",
        "contractType": "self_employed_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/rua-somadomain-ru",
      "email": "rua@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4807",
        "firstName": "Антон",
        "lastName": "Рулёв",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/69fcf84e-7bba-11ed-ba3e-b272947b9265",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/f04ba2a8-7aaa-11ed-8a5a-b272947b9265",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
      ],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/rir-somadomain-ru",
      "email": "rir@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-09-14T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4824",
        "firstName": "Ирина",
        "lastName": "Рычкова",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/ea8de222-7980-11eb-b707-bea64491cdb5",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_10,
project_1,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/240",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Веб-дизайнер 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/rek-somadomain-ru",
      "email": "rek@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4847",
        "firstName": "Екатерина",
        "lastName": "Ряполова",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/8f5f9076-bb0b-11ec-a32b-0a8f35a47480",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": null,
      "projectsAsManager": [
project_3,
        project_8,
      ],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": false,
      "isHR": true,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/saa-somadomain-ru",
      "email": "saa@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-07-05T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4909",
        "firstName": "Анастасия",
        "lastName": "Сапега",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 11
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/1e187780-dd5c-11eb-b6f0-3eb99a117d7c",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_6,
        project_5,
project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/93",
        "@type": "WorkPosition",
        "datePosition": "2021-07-05T00:00:00+05:00",
        "jobTitle": "дизайнер 2 категории",
        "contractType": "foreigner_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/sae-somadomain-ru",
      "email": "sae@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-11-19T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4920",
        "firstName": "Евгений",
        "lastName": "Сапов",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/4af12ee4-462b-11ed-8782-7a6aa26374bc",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/89cc84e4-412a-11ec-8c40-b2f8ae0b087e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
project_1,
        project_2
      ],
      "projectsAsDeveloper": [
        project_6,
project_1,
        project_4,
      ],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": {
        "@id": "/api/work-positions/266",
        "@type": "WorkPosition",
        "datePosition": "2022-10-03T00:00:00+05:00",
        "jobTitle": "Ведущий разработчик",
        "contractType": "labor_contract",
        "normFullDay": 4,
        "normShortDay": 3,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/fs-somadomain-ru",
      "email": "fs@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:4995",
        "firstName": "Федор",
        "lastName": "Селиванов",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/dc97364e-572c-11eb-ace4-ed76ae2ad0f5",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": null,
      "projectsAsManager": [],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": false,
      "isHR": true,
      "workPosition": null
    },    
    {
      "@type": "User",
      "@id": "/api/users/das-somadomain-ru",
      "email": "das@somedomain.com",
      "contacts": [],
      "dateHiring": "2020-11-03T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:5075",
        "firstName": "Даниил",
        "lastName": "Соколов",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 8
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/e6336ce4-56fb-11eb-9cc0-f5ef4e941ba3",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_7,
        project_5
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/245",
        "@type": "WorkPosition",
        "datePosition": "2022-07-01T00:00:00+05:00",
        "jobTitle": "Разработчик 1 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/son-somadomain-ru",
      "email": "son@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-12-02T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:5084",
        "firstName": "Наталья",
        "lastName": "Сорокина",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 9
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/a9607b32-5366-11ec-b6c7-7e64e3170ae9",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
project_1,
        project_4,
        project_11
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/247",
        "@type": "WorkPosition",
        "datePosition": "2022-09-01T00:00:00+05:00",
        "jobTitle": "Специалист по ручному тестированию в области информационных технологий 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/stm-somadomain-ru",
      "email": "stm@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:5107",
        "firstName": "Милана",
        "lastName": "Студинская",
        "surname": null,
        "gender": "Female",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/9d0af39a-5f6c-11ed-98f6-ce2f37c7c439",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/nis-somadomain-ru",
      "email": "nis@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-08-09T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:5125",
        "firstName": "Николай",
        "lastName": "Сульженко",
        "surname": "Рудольфович",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/4d3084e4-d5dc-11ec-808d-be41b03b6e16",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/1cf12e4e-f8d5-11eb-81d4-325b06ee5663",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
        project_2
      ],
      "projectsAsDeveloper": [
project_1,
        project_8,
        project_4,
        project_6
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": {
        "@id": "/api/work-positions/290",
        "@type": "WorkPosition",
        "datePosition": "2023-04-01T00:00:00+05:00",
        "jobTitle": "Технический эксперт 3 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/as-somadomain-ru",
      "email": "as@somedomain.com",
      "contacts": [],
      "dateHiring": "2014-09-18T00:00:00+06:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:1497",
        "firstName": "Алексей",
        "lastName": "Сырчин",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/50d339b6-f34d-11ea-8547-91b0dee78ba3",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": null,
      "projectsAsManager": [],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": false,
      "isHR": true,
      "workPosition": {
        "@id": "/api/work-positions/143",
        "@type": "WorkPosition",
        "datePosition": "2014-09-18T00:00:00+06:00",
        "jobTitle": "Исполнительный директор",
        "contractType": "labor_contract",
        "normFullDay": 0,
        "normShortDay": 0,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/un-somadomain-ru",
      "email": "un@somedomain.com",
      "contacts": [],
      "dateHiring": null,
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:1624",
        "firstName": "Николай",
        "lastName": "Упоров",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": {
        "@type": "Manager",
        "@id": "/api/managers/6d001540-54ab-11eb-8024-9ba8a55651ac",
        "firstName": null,
        "lastName": null,
        "surname": null
      },
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/87a49d9c-a16d-11ed-aa2c-d2ad45816a6c",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [
project_1
      ],
      "projectsAsDeveloper": [],
      "isAdmin": false,
      "isManager": true,
      "isMasterManager": true,
      "isDeveloper": true,
      "isHR": true,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/evu-somadomain-ru",
      "email": "evu@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-04-05T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:1741",
        "firstName": "Евгений",
        "lastName": "Усов",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/4ba4e7a8-95e3-11eb-84e1-5e5d907de3f3",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/267",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 3 категории ",
        "contractType": "labor_contract",
        "normFullDay": 7,
        "normShortDay": 6,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/dfi-somadomain-ru",
      "email": "dfi@somedomain.com",
      "contacts": [],
      "dateHiring": "2019-11-29T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2099",
        "firstName": "Денис",
        "lastName": "Фишкинд",
        "surname": "Андреевич",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/a1ea425a-7a5b-11eb-9b7a-46f18f19bd2b",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_5
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/273",
        "@type": "WorkPosition",
        "datePosition": "2022-11-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/kha-somadomain-ru",
      "email": "kha@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-02-22T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2358",
        "firstName": "Андрей",
        "lastName": "Халиманенков",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 10
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/0e9571da-9532-11ec-9783-121818355f04",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_1,
        project_2
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/186",
        "@type": "WorkPosition",
        "datePosition": "2022-10-10T00:00:00+05:00",
        "jobTitle": "Разработчик 3 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/har-somadomain-ru",
      "email": "har@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-07-27T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2401",
        "firstName": "Радик",
        "lastName": "Хамматов",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 6
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/6d667d2c-eebf-11eb-808a-325b06ee5663",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_2,
        project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/269",
        "@type": "WorkPosition",
        "datePosition": "2022-08-01T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории ",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/hoa-somadomain-ru",
      "email": "hoa@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-10-18T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2692",
        "firstName": "Андрей",
        "lastName": "Хожемпо",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 3
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/1c93e126-4e1a-11ed-bfad-7a6aa26374bc",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_1,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/275",
        "@type": "WorkPosition",
        "datePosition": "2022-10-18T00:00:00+05:00",
        "jobTitle": "Разработчик на языке программирования Golang 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/vsh-somadomain-ru",
      "email": "vsh@somedomain.com",
      "contacts": [],
      "dateHiring": "2022-11-03T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2817",
        "firstName": "Вахтанг",
        "lastName": "Шенгелия",
        "surname": null,
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 3
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/69efaf82-5b5c-11ed-87e6-ce2f37c7c439",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_1,
        project_11
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/276",
        "@type": "WorkPosition",
        "datePosition": "2022-11-03T00:00:00+05:00",
        "jobTitle": "Разработчик 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/shi-somadomain-ru",
      "email": "shi@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-04-01T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2851",
        "firstName": "Ирина",
        "lastName": "Широкова",
        "surname": "Анатольевна",
        "gender": "Female",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/858f43d0-7a7e-11eb-8a72-962e4e1da94e",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_10,
        project_4,
        project_2,
        project_5
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/51",
        "@type": "WorkPosition",
        "datePosition": "2021-04-01T00:00:00+05:00",
        "jobTitle": "Разработчик 1 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/enn-somadomain-ru",
      "email": "enn@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-05-31T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
        "@type": "Person",
        "@id": "_:2891",
        "firstName": "Никита",
        "lastName": "Энес",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/5d8409c2-c1ee-11eb-8662-aaa215f9d1ba",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_1,
        project_7,
        project_9,
        project_4,
        project_6,
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
        "@id": "/api/work-positions/249",
        "@type": "WorkPosition",
        "datePosition": "2022-10-01T00:00:00+05:00",
        "jobTitle": "Веб-дизайнер 2 категории",
        "contractType": "labor_contract",
        "normFullDay": 8,
        "normShortDay": 7,
        "datePositionEnd": null,
        "workingStatus": "in_work"
      }
    },
    {
      "@type": "User",
      "@id": "/api/users/yap-somadomain-ru",
      "email": "yap@somedomain.com",
      "contacts": [],
      "dateHiring": "2019-08-16T00:00:00+05:00",
      "dateDismissal": "2023-03-06T00:00:00+05:00",
      "person": {
        "@type": "Person",
        "@id": "_:3144",
        "firstName": "Ян",
        "lastName": "Янченко",
        "surname": "",
        "gender": "Male",
        "birthDate": null,
        "jobTitle": null,
        "city": 1
      },
      "manager": null,
      "developer": {
        "@type": "Developer",
        "@id": "/api/developers/ad2eeb8c-56fe-11eb-bdef-fb480bc2582b",
        "firstName": null,
        "lastName": null,
        "surname": null,
        "dateHiring": null,
        "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
        project_1
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": null
    },
    {
      "@type": "User",
      "@id": "/api/users/bav-somadomain-ru",
      "email": "bav@somedomain.com",
      "contacts": [],
      "dateHiring": "2021-03-04T00:00:00+05:00",
      "dateDismissal": null,
      "person": {
          "@type": "Person",
          "@id": "_:2801",
          "firstName": "Вадим",
          "lastName": "Бардачев",
          "surname": "",
          "gender": "Male",
          "birthDate": null,
          "jobTitle": null,
          "city": 7
      },
      "manager": null,
      "developer": {
          "@type": "Developer",
          "@id": "/api/developers/0148225a-7cad-11eb-ba66-02c3af079440",
          "firstName": null,
          "lastName": null,
          "surname": null,
          "dateHiring": null,
          "dateDismissal": null
      },
      "projectsAsManager": [],
      "projectsAsDeveloper": [
      ],
      "isAdmin": false,
      "isManager": false,
      "isMasterManager": false,
      "isDeveloper": true,
      "isHR": false,
      "workPosition": {
          "@id": "/api/work-positions/10",
          "@type": "WorkPosition",
          "datePosition": "2021-03-04T00:00:00+05:00",
          "jobTitle": "Программист 2 категории (middle)",
          "contractType": "labor_contract",
          "normFullDay": 8,
          "normShortDay": 7,
          "datePositionEnd": null,
          "workingStatus": "in_work"
      }
  }
  ]