import { IProject } from "entities/project/project.types";

export const projects: IProject[] = [
        {
            "@type": "Project",
            "@id": "/api/projects/project-1",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/a02ebe74-d20a-11ed-8571-6e96a8b65f3e",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 1,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-2",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/0de76ec2-4ed3-11ed-b440-7a6aa26374bc",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-3",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/4bb98788-ab9b-11ed-8e1c-ea3e34fa79ed",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-4",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/f72d77b0-cf37-11eb-863b-06d5ef3c9008",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-5",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/f72d77b0-cf37-11eb-863b-06d5ef3c9008",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-6",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/08005e42-d2a5-11ec-811d-32a319214716",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 8,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-7",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/f82431a0-7801-11eb-8ee5-169d465aadad",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-8",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/59db7e74-201a-11ec-a2c6-a63b6f55ceb2",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 1,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-9",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/9e957670-f31b-11ed-b9bd-622e2f465016",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 2,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-10",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/abd8a722-5518-11ed-b138-7a6aa26374bc",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-11",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/3755b170-d86b-11ed-a742-6e96a8b65f3e",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 1,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-12",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/78aeb2b6-d2a4-11ec-b463-32a319214716",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 2,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-13",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/4a49bf4e-d41a-11eb-8d9e-3eb99a117d7c",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-14",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/61b1c1ce-29cb-11ed-8f69-fe6263566c11",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 2,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-15",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/afd96542-c97f-11ed-8bc3-6e96a8b65f3e",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-16",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/54636db6-d2a4-11ec-b4f2-32a319214716",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-17",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/eead850a-d2a4-11ec-bee0-32a319214716",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },        
        {
            "@type": "Project",
            "@id": "/api/projects/project-18",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/649c25b8-cee0-11ed-b67a-6e96a8b65f3e",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 1,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-19",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/262ff158-5f26-11ed-a5d2-ce2f37c7c439",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
        {
            "@type": "Project",
            "@id": "/api/projects/project-20",
            "title": "Проект",
            "description": "Проект Компании",
            "contractor": {
                "@id": "/api/contractors/21bdb3fe-4ea9-11ed-b743-7a6aa26374bc",
                "@type": "Contractor",
                "shortName": "Компания",
                "fullName": "Компания"
            },
            "stages": [],
            "currentStage": null,
            "archived": false,
            "isCommercial": true,
            city: 3,
        },
    ];