import { IDeveloperWorkInfo, IGradeState } from "./grade.types";

export const workInfo: {[K in string]: IDeveloperWorkInfo | null} = {
        "aba@somedomain.com": null,
        "abr@somedomain.com": null,
        "ahi@somedomain.com": null,
        "bann@somedomain.com": null,
        "mba@somedomain.com": null,
        "ben@somedomain.com": null,
        "boa@somedomain.com": null,
        "yub@somedomain.com": null,
        "vav@somedomain.com": null,
        "vol@somedomain.com": null,
        "vog@somedomain.com": null,
        "gak@somedomain.com": null,
        "gou@somedomain.com": null,
        "guk@somedomain.com": null,
        "dma@somedomain.com": null,
        "eva@somedomain.com": null,
        "aer@somedomain.com": null,
        "zvd@somedomain.com": null,
        "hrd@somedomain.com": null,
        "idm@somedomain.com": {
                type: "Backend",
                grades: ["Junior", "Pre-Middle", "Middle", "Upper-Middle", "Senior", "TeamLead"],
                stack: [],
        },
        "kaa@somedomain.com": null,
        "ek@somedomain.com": null,
        "ki@somedomain.com": null,
        "fin@somedomain.com": null,
        "ok@somedomain.com": null,
        "kot@somedomain.com": null,
        "kud@somedomain.com": null,
        "bok@somedomain.com": null,
        "lad@somedomain.com": null,
        "mev@somedomain.com": null,
        "mod@somedomain.com": null,
        "mukd@somedomain.com": null,
        "nem@somedomain.com": null,
        "ovv@somedomain.com": null,
        "valp@somedomain.com": null,
        "peg@somedomain.com": null,
        "ram@somedomain.com": null,
        "rua@somedomain.com": null,
        "rir@somedomain.com": null,
        "rek@somedomain.com": null,
        "saa@somedomain.com": null,
        "sae@somedomain.com": null,
        "fs@somedomain.com": null,
        "das@somedomain.com": null,
        "son@somedomain.com": null,
        "stm@somedomain.com": null,
        "nis@somedomain.com": null,
        "as@somedomain.com": null,
        "un@somedomain.com": null,
        "evu@somedomain.com": null,
        "dfi@somedomain.com": null,
        "kha@somedomain.com": null,
        "har@somedomain.com": null,
        "hoa@somedomain.com": null,
        "vsh@somedomain.com": null,
        "shi@somedomain.com": {
                type: "Frontend",
                grades: ["Junior", "Pre-Middle", "Middle", "Upper-Middle"],
                stack: ["ReactJS", "JavaScript", "TypeScript", "CSS", "ReduxToolkit"]
        },
        "enn@somedomain.com": null
}

export const INITIAL_STATE:IGradeState = {
        error: null,
        items: [],
        loading: "idle",
}