import { ICity } from "./city.types";

export const cities: ICity[] = [
    {
        "id": 1,
        "country_id": 130,
        "name": "Тюмень",
        "title": "Tyumen",
        "value": "TMN",
        "region_id": 72,
        "timezone": "(GMT+5)",
    },
    {
        "id": 2,
        "country_id": 130,
        "name": "Санкт-Петербург",
        "title": "Saint Pitersburg",
        "value": "SPT",
        "region_id": 36,
        "timezone": "(GMT+3)",
    },
    {
        "id": 3,
        "country_id": 130,
        "name": "Москва",
        "title": "Moscow",
        "value": "MSK",
        "region_id": 38,
        "timezone": "(GMT+3)",
    },
    {
        "id": 4,
        "country_id": 130,
        "name": "Симферополь",
        "title": "Simpheropol",
        "value": "SMP",
        "region_id": null,
        "timezone": "(GMT+3)",
    },
    {
        "id": 5,
        "country_id": 130,
        "name": "Новосибирск",
        "title": "Novosibirsk",
        "value": "NVS",
        "region_id": 47,
        "timezone": "(GMT+7)",
    },
    {
        "id": 6,
        "country_id": 130,
        "name": "Казань",
        "title": "Kazan",
        "value": "KZN",
        "region_id": 69,
        "timezone": "(GMT+3)",
    },
    {
        "id": 7,
        "country_id": 130,
        "name": "Краснодар",
        "title": "Krasnodar",
        "value": "KRS",
        "region_id": 20,
        "timezone": "(GMT+3)",
    },
    {
        "id": 8,
        "country_id": 130,
        "name": "Екатеринбург",
        "title": "Ekaterinburg",
        "value": "EKB",
        "region_id": 65,
        "timezone": "(GMT+5)",
    },
    {
        "id": 9,
        "country_id": 130,
        "name": "Балашиха",
        "title": "Balashiha",
        "value": "BLS",
        "region_id": 43,
        "timezone": "(GMT+3)",
    },
    {
        "id": 10,
        "country_id": 130,
        "name": "Биробиджан",
        "title": "Birobidzan",
        "value": "BRZ",
        "region_id": 81,
        "timezone": "(GMT+10)",
    },
    {
        "id": 11,
        "country_id": 27,
        "name": "Бобруйск",
        "title": "Bobruisk",
        "value": "BBR",
        "region_id": null,
        "timezone": "(GMT+3)",
    },
    {
        "id": 12,
        "country_id": 130,
        "name": "Пушкино",
        "title": "Pushkino",
        "value": "PSK",
        "region_id": 43,
        "timezone": "(GMT+3)",
    },
    {
        "id": 13,
        "country_id": 130,
        "name": "Рыбинск",
        "title": "Rybinsk",
        "value": "RBK",
        "region_id": 80,
        "timezone": "(GMT+3)",
    },
    {
        "id": 14,
        "country_id": 85,
        "name": "Астана",
        "title": "Astana",
        "value": "AST",
        "region_id": null,
        "timezone": "(GMT+6)",
    },
    {
        "id": 15,
        "country_id": 56,
        "name": "Батуми",
        "title": "Batumi",
        "value": "BTM",
        "region_id": null,
        "timezone": "(GMT+4)",
    },
    {
        "id": 16,
        "country_id": 27,
        "name": "Жлобин",
        "title": "Zhlobin",
        "value": "ZHL",
        "region_id": null,
        "timezone": "(GMT+3)",
    },
    {
        "id": 17,
        "country_id": 130,
        "name": "Южно-Сахалинск",
        "title": "Yuzhno-Sakhalinsk",
        "value": "UZSK",
        "region_id": 60,
        "timezone": "(GMT+11)",
    },
    {
        "id": 18,
        "country_id": 85,
        "name": "Петропавловск",
        "title": "Petropavlovsk",
        "value": "PPVL",
        "region_id": null,
        "timezone": "(GMT+6)",
    },
    {
        "id": 19,
        "country_id": 150,
        "name": "Тайланд",
        "title": "Thailand",
        "value": "THLND",
        "region_id": null,
        "timezone": "(GMT+7)",
    }
]